### ISSUE TITLE
No async?

### ISSUE THREAD

**Issue by Cellus250** [seatsio/seatsio-dotnet#55]
Hello. I am just getting started with the package, but there appears to be no async requests. Is there a reason for this?

**Comment by mroloux** [comment]
Hi!

async calls are on our todo (or at least "to investigate") list.

We don't have any .NET experts on the team to be honest. Are async calls the preferred way to talk to an API?

**Comment by Cellus250** [comment]
Okay, no worries and thanks for the response. But yes, async is pretty much the standard for communicating with APIs.

I'll go ahead and close this issue.
