### ISSUE TITLE
Outdated RestSharp library

### ISSUE THREAD

**Issue by markafox** [seatsio/seatsio-dotnet#60]
Seatios IO is using a legacy version of RestSharp and when RestSharp is updated Seats.io throws the following error:

System.MissingMethodException: Method not found: 'RestSharp.IRestClient RestSharp.RestClientExtensions.AddDefaultHeader(RestSharp.IRestClient, System.String, System.String)'.

  Stack Trace: 
SeatsioClient.CreateRestClient(String secretKey, String workspaceKey, String baseUrl)
SeatsioClient.ctor(String secretKey, String workspaceKey, String baseUrl)
SeatsioClient.ctor(Region region, String secretKey, String workspaceKey)
SeatsioClient.ctor(Region region, String secretKey)
...

**Comment by mroloux** [comment]
Hi,

We'll have a look at that. It seems the RestSharp API changed quite a lot in recent versions, so it might not be so easy for us to upgrade 😉 But we'll give it a try.

**Comment by mroloux** [comment]
We just released v91.0.0, which contains the latest RestSharp release as a dependency. Thanks for reporting this!
